### ISSUE TITLE
Import/Download brushes broken

### ISSUE THREAD

**Issue by secretgspot** [Pullusb/greasepencil_tools#20]
After initial activation of addon on 3.1 everything seemed normal and clicking down arrow on brush tool area showed option to download/import additional brushes, however after restarting blender or starting new option, all of the imported/downloaded brushes disappeared along with option to reimport them.  Trying to toggle an addon gave an error 

Traceback (most recent call last):
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\addons\greasepencil_tools\__init__.py", line 45, in register
    prefs.register()
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\addons\greasepencil_tools\prefs.py", line 285, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'GPTS_timeline_settings'

**Comment by Pullusb** [comment]
Hi, thanks for reporting,
Are you using the build in addon version ? if that's the case, see issue #18

**Comment by Pullusb** [comment]
Closing issue since this feature was stripped of the addon long time ago.
